import { Bike, Rental, Station } from "./types";

export const mockStations: Station[] = [
  {
    id: "STN001",
    name: "Central Park West",
    location: "41.8781° N, 87.6298° W",
    capacity: 20,
    bikesAvailable: 15,
  },
  {
    id: "STN002",
    name: "Millennium Park",
    location: "41.8826° N, 87.6226° W",
    capacity: 25,
    bikesAvailable: 10,
  },
  {
    id: "STN003",
    name: "Navy Pier",
    location: "41.8917° N, 87.6094° W",
    capacity: 30,
    bikesAvailable: 28,
  },
  {
    id: "STN004",
    name: "Lincoln Park Zoo",
    location: "41.9216° N, 87.6338° W",
    capacity: 15,
    bikesAvailable: 5,
  },
  {
    id: "STN005",
    name: "River North",
    location: "41.8920° N, 87.6322° W",
    capacity: 22,
    bikesAvailable: 22,
  },
];

export const mockBikes: Bike[] = [
  {
    id: "BIKE001",
    qrCode: "GP-001",
    status: "AVAILABLE",
    batteryLevel: 95,
    stationId: "STN001",
    stationName: "Central Park West",
  },
  {
    id: "BIKE002",
    qrCode: "GP-002",
    status: "IN_USE",
    batteryLevel: 67,
    stationId: null,
  },
  {
    id: "BIKE003",
    qrCode: "GP-003",
    status: "MAINTENANCE",
    batteryLevel: 100,
    stationId: "STN002",
    stationName: "Millennium Park",
  },
  {
    id: "BIKE004",
    qrCode: "GP-004",
    status: "MAINTENANCE",
    batteryLevel: 20,
    stationId: "STN001",
    stationName: "Central Park West",
  },
  {
    id: "BIKE005",
    qrCode: "GP-005",
    status: "AVAILABLE",
    batteryLevel: 88,
    stationId: "STN003",
    stationName: "Navy Pier",
  },
  {
    id: "BIKE006",
    qrCode: "GP-006",
    status: "IN_USE",
    batteryLevel: 45,
    stationId: null,
  },
  {
    id: "BIKE007",
    qrCode: "GP-007",
    status: "AVAILABLE",
    batteryLevel: 76,
    stationId: "STN004",
    stationName: "Lincoln Park Zoo",
  },
  {
    id: "BIKE008",
    qrCode: "GP-008",
    status: "AVAILABLE",
    batteryLevel: 91,
    stationId: "STN003",
    stationName: "Navy Pier",
  },
];

export const mockRentals: Rental[] = [
  {
    id: "RNT001",
    userId: "USR001",
    userName: "Alice Johnson",
    bikeId: "BIKE002",
    startTime: new Date(Date.now() - 3600000 * 0.5),
    endTime: null,
    cost: null,
    status: "ACTIVE",
  },
  {
    id: "RNT002",
    userId: "USR002",
    userName: "Bob Williams",
    bikeId: "BIKE006",
    startTime: new Date(Date.now() - 3600000 * 1.2),
    endTime: null,
    cost: null,
    status: "ACTIVE",
  },
  {
    id: "RNT003",
    userId: "USR003",
    userName: "Charlie Brown",
    bikeId: "BIKE001",
    startTime: new Date(Date.now() - 3600000 * 24 * 1),
    endTime: new Date(Date.now() - 3600000 * 23),
    cost: 15.5,
    status: "COMPLETED",
  },
  {
    id: "RNT004",
    userId: "USR001",
    userName: "Alice Johnson",
    bikeId: "BIKE005",
    startTime: new Date(Date.now() - 3600000 * 24 * 2),
    endTime: new Date(Date.now() - 3600000 * 22),
    cost: 25.0,
    status: "COMPLETED",
  },
  {
    id: "RNT005",
    userId: "USR004",
    userName: "David Miller",
    bikeId: "BIKE003",
    startTime: new Date(Date.now() - 3600000 * 24 * 3),
    endTime: new Date(Date.now() - 3600000 * 22.5),
    cost: 18.75,
    status: "COMPLETED",
  },
];

export const mockRevenueData = [
  { name: "Jan", total: Math.floor(Math.random() * 5000) + 1000 },
  { name: "Feb", total: Math.floor(Math.random() * 5000) + 1000 },
  { name: "Mar", total: Math.floor(Math.random() * 5000) + 1000 },
  { name: "Apr", total: Math.floor(Math.random() * 5000) + 1000 },
  { name: "May", total: Math.floor(Math.random() * 5000) + 1000 },
  { name: "Jun", total: Math.floor(Math.random() * 5000) + 1000 },
  { name: "Jul", total: Math.floor(Math.random() * 5000) + 1000 },
  { name: "Aug", total: Math.floor(Math.random() * 5000) + 1000 },
  { name: "Sep", total: Math.floor(Math.random() * 5000) + 1000 },
  { name: "Oct", total: Math.floor(Math.random() * 5000) + 1000 },
  { name: "Nov", total: Math.floor(Math.random() * 5000) + 1000 },
  { name: "Dec", total: Math.floor(Math.random() * 5000) + 1000 },
];
